import pandas as pd

# Banco de dados expandido de jogos PS2
ps2_games_database = [
    # Jogos originais
    {
        "title": "Shadow of the Colossus",
        "genre": "Action-Adventure",
        "year": 2005,
        "developer": "Team Ico",
        "publisher": "Sony Computer Entertainment",
        "rating": 91,
        "description": "Um jovem chamado Wander parte para reviver uma garota sacrificada, enfrentando 16 colossos em uma terra proibida.",
        "characters": "Wander, Mono, Agro",
        "gameplay_mechanics": "Exploração em mundo aberto, escalada de colossos, uso de espada e arco",
        "trivia": "Considerado uma obra de arte, foi remasterizado para PS3 e PS4.",
        "tips_easter_eggs": "A espada aponta para o próximo colosso quando exposta à luz solar."
    },
    {
        "title": "God of War II",
        "genre": "Hack and Slash",
        "year": 2007,
        "developer": "Santa Monica Studio",
        "publisher": "Sony Computer Entertainment",
        "rating": 93,
        "description": "Kratos busca vingança contra Zeus após ser traído, em uma jornada épica através da mitologia grega.",
        "characters": "Kratos, Zeus, Gaia, Athena",
        "gameplay_mechanics": "Combate visceral, quebra-cabeças, quick time events",
        "trivia": "Utilizou 35MB de dados apenas para os músculos do modelo 3D de Kratos.",
        "tips_easter_eggs": "Na cena do Cavalo Alado, voe além dos limites do mapa para encontrar um easter egg."
    },
    
    # Jogos adicionados anteriormente
    {
        "title": "Metal Gear Solid 3: Snake Eater",
        "genre": "Stealth",
        "year": 2004,
        "developer": "Kojima Productions",
        "publisher": "Konami",
        "rating": 91,
        "description": "Operação na Guerra Fria onde Naked Snake infiltra-se na Rússia para resgatar um cientista.",
        "characters": "Naked Snake, The Boss, Ocelot, Eva",
        "gameplay_mechanics": "Camuflagem, sistema de cura, combate CQC",
        "trivia": "O jogo tem múltiplas cenas que mudam conforme suas ações.",
        "tips_easter_eggs": "Deixe o jogo pausado por uma semana real para vencer um chefe automaticamente."
    },
    {
        "title": "Grand Theft Auto: San Andreas",
        "genre": "Action-Adventure",
        "year": 2004,
        "developer": "Rockstar North",
        "publisher": "Rockstar Games",
        "rating": 95,
        "description": "Carl Johnson retorna a Los Santos e se envolve em gangues enquanto desvenda o assassinato de sua mãe.",
        "characters": "CJ, Sweet, Big Smoke, Ryder, Officer Tenpenny",
        "gameplay_mechanics": "Mundo aberto, personalização de personagem, diversas armas e veículos",
        "trivia": "O mapa é baseado em cidades reais da Califórnia como LA e San Francisco.",
        "tips_easter_eggs": "Digite 'HESOYAM' para ganhar saúde, armadura e $250.000."
    },
    
    # Novos jogos adicionados
    {
        "title": "Resident Evil 4",
        "genre": "Survival Horror",
        "year": 2005,
        "developer": "Capcom",
        "publisher": "Capcom",
        "rating": 96,
        "description": "Leon S. Kennedy é enviado para resgatar a filha do presidente em uma vila rural infestada por parasitas.",
        "characters": "Leon S. Kennedy, Ashley Graham, Ada Wong, Luis Sera",
        "gameplay_mechanics": "Sistema de mira over-the-shoulder, inventário limitado, combate tático",
        "trivia": "Revolucionou o gênero e influenciou muitos jogos de tiro em terceira pessoa.",
        "tips_easter_eggs": "Complete o jogo em menos de 5 horas para desbloquear a Chicago Typewriter."
    },
    {
        "title": "Persona 4",
        "genre": "RPG",
        "year": 2008,
        "developer": "Atlus",
        "publisher": "Atlus",
        "rating": 90,
        "description": "Um estudante se muda para Inaba e investiga assassinatos ligados a um mundo dentro das TVs.",
        "characters": "Yu Narukami, Yosuke, Chie, Yukiko, Kanji",
        "gameplay_mechanics": "Combate por turnos, Social Links, gerenciamento de tempo",
        "trivia": "Teve adaptações para anime, mangá e até musical.",
        "tips_easter_eggs": "Maximize todos os Social Links para o final verdadeiro."
    },
    {
        "title": "Okami",
        "genre": "Action-Adventure",
        "year": 2006,
        "developer": "Clover Studio",
        "publisher": "Capcom",
        "rating": 93,
        "description": "Amaterasu, a deusa lobo, usa seu pincel celestial para restaurar a beleza ao mundo.",
        "characters": "Amaterasu, Issun, Susano'o",
        "gameplay_mechanics": "Sistema de pintura celestial, combate estilo hack and slash",
        "trivia": "A arte foi inspirada em pinturas tradicionais japonesas.",
        "tips_easter_eggs": "Desenhe um círculo ao redor da lua cheia para transformar a noite em dia."
    },
    {
        "title": "Burnout 3: Takedown",
        "genre": "Racing",
        "year": 2004,
        "developer": "Criterion Games",
        "publisher": "EA Games",
        "rating": 94,
        "description": "Corridas de alta velocidade com ênfase em colisões espetaculares e manobras arriscadas.",
        "characters": "N/A",
        "gameplay_mechanics": "Sistema de Takedown, modos de colisão, boost por manobras",
        "trivia": "Considerado por muitos como o melhor jogo da série Burnout.",
        "tips_easter_eggs": "Nas pistas com trânsito, colidir com ônibus causa acidentes maiores."
    },
    {
        "title": "Dragon Quest VIII: Journey of the Cursed King",
        "genre": "RPG",
        "year": 2004,
        "developer": "Level-5",
        "publisher": "Square Enix",
        "rating": 89,
        "description": "Um herói silencioso busca quebrar a maldição que transformou o rei em um troll.",
        "characters": "Hero, Yangus, Jessica, Angelo",
        "gameplay_mechanics": "Combate por turnos, sistema de habilidades, alquimia",
        "trivia": "Primeiro Dragon Quest com gráficos 3D e dublagem completa.",
        "tips_easter_eggs": "Derrote o Dragão Prateado no início do jogo para um desafio épico."
    },
    {
        "title": "Prince of Persia: The Sands of Time",
        "genre": "Action-Adventure",
        "year": 2003,
        "developer": "Ubisoft Montreal",
        "publisher": "Ubisoft",
        "rating": 92,
        "description": "O Príncipe doa Pérsia acidentalmente liberta as Areias do Tempo e deve consertar seu erro.",
        "characters": "Prince, Farah, Vizier",
        "gameplay_mechanics": "Parkour, combate acrobático, rewind time",
        "trivia": "O jogo quase foi cancelado durante o desenvolvimento.",
        "tips_easter_eggs": "No menu principal, digite 'DIE' para ouvir uma piada do Príncipe."
    },
    {
        "title": "Guitar Hero II",
        "genre": "Rhythm",
        "year": 2006,
        "developer": "Harmonix",
        "publisher": "RedOctane",
        "rating": 92,
        "description": "Simulador de guitarra com sucessos do rock e um controle especial em forma de guitarra.",
        "characters": "Vários avatares customizáveis",
        "gameplay_mechanics": "Five-button guitar controller, star power, multiplayer",
        "trivia": "O jogo vendeu mais de 1.3 milhão de cópias nos primeiros 3 meses.",
        "tips_easter_eggs": "Complete todas as músicas no Expert para desbloquear a canção secreta."
    },
    {
        "title": "Silent Hill 2",
        "genre": "Survival Horror",
        "year": 2001,
        "developer": "Team Silent",
        "publisher": "Konami",
        "rating": 89,
        "description": "James Sunderland recebe uma carta de sua esposa morta e vai para Silent Hill, encontrando horrores pessoais.",
        "characters": "James, Maria, Pyramid Head, Angela",
        "gameplay_mechanics": "Atmosfera psicológica, quebra-cabeças, combate limitado",
        "trivia": "Pyramid Head foi inspirado em executores medievais.",
        "tips_easter_eggs": "Existem 6 finais diferentes baseados em suas ações."
    },
    {
        "title": "Jak II",
        "genre": "Action-Adventure",
        "year": 2003,
        "developer": "Naughty Dog",
        "publisher": "Sony Computer Entertainment",
        "rating": 87,
        "description": "Jak é experimentado com Dark Eco e ganha poderes enquanto tenta derrubar um regime opressivo.",
        "characters": "Jak, Daxter, Keira, Baron Praxis",
        "gameplay_mechanics": "Plataforma 3D, veículos, armas futuristas",
        "trivia": "Mudou drasticamente o tom em relação ao primeiro jogo.",
        "tips_easter_eggs": "Encontre todos os Orbs para desbloquear segredos."
    },
    
    # Jogos adicionais
    {
        "title": "Final Fantasy X",
        "genre": "RPG",
        "year": 2001,
        "developer": "Square",
        "publisher": "Square",
        "rating": 92,
        "description": "Tidus é transportado para o mundo de Spira, onde ajuda a invocadora Yuna em sua peregrinação para derrotar Sin.",
        "characters": "Tidus, Yuna, Auron, Wakka, Lulu, Rikku, Kimahri",
        "gameplay_mechanics": "Conditional Turn-Based Battle, Sphere Grid, invocações",
        "trivia": "Primeiro Final Fantasy com vozes e o último dirigido por Hironobu Sakaguchi.",
        "tips_easter_eggs": "Capture monstros no Calm Lands para formar seu próprio time de batalha."
    },
    {
        "title": "Kingdom Hearts",
        "genre": "Action-RPG",
        "year": 2002,
        "developer": "Square",
        "publisher": "Square",
        "rating": 85,
        "description": "Sora viaja entre mundos inspirados em filmes Disney junto com Donald e Pateta para combater os Heartless.",
        "characters": "Sora, Riku, Kairi, Donald, Goofy, Mickey",
        "gameplay_mechanics": "Combate em tempo real, magias, aliados da Disney",
        "trivia": "Surgiu de uma conversa casual de elevador entre executivos da Square e Disney.",
        "tips_easter_eggs": "Derrote Sephiroth no Coliseu para obter a Keyblade mais poderosa."
    },
    {
        "title": "Tony Hawk's Pro Skater 3",
        "genre": "Sports",
        "year": 2001,
        "developer": "Neversoft",
        "publisher": "Activision",
        "rating": 97,
        "description": "Simulador de skate com level design aberto, manobras complexas e desafios variados.",
        "characters": "Tony Hawk, Rodney Mullen, Steve Caballero, outros skatistas profissionais",
        "gameplay_mechanics": "Sistema de manobras encadeadas, revert, park editor",
        "trivia": "Foi o primeiro jogo online para PlayStation 2.",
        "tips_easter_eggs": "Combine revert com manual para conseguir combos infinitos."
    },
    {
        "title": "Devil May Cry 3: Dante's Awakening",
        "genre": "Hack and Slash",
        "year": 2005,
        "developer": "Capcom",
        "publisher": "Capcom",
        "rating": 84,
        "description": "Prequel onde Dante enfrenta seu irmão gêmeo Vergil que tenta abrir um portal para o mundo demoníaco.",
        "characters": "Dante, Vergil, Lady, Arkham",
        "gameplay_mechanics": "Estilos de luta, armas únicas, sistema de ranking de combate",
        "trivia": "A primeira versão era tão difícil que a Capcom lançou uma versão especial mais equilibrada.",
        "tips_easter_eggs": "Aperte L3 + R3 durante o jogo para acessar o Modo Super Dante."
    },
    {
        "title": "ICO",
        "genre": "Puzzle-Adventure",
        "year": 2001,
        "developer": "Team Ico",
        "publisher": "Sony Computer Entertainment",
        "rating": 90,
        "description": "Um menino com chifres tenta escapar de um castelo enquanto protege uma garota misteriosa.",
        "characters": "Ico, Yorda, A Rainha",
        "gameplay_mechanics": "Puzzles ambientais, combate minimalista, guiar Yorda pelo castelo",
        "trivia": "A capa ocidental do jogo foi criticada pelo criador Fumito Ueda por ser muito comercial.",
        "tips_easter_eggs": "Complete o jogo uma vez para desbloquear o modo espelhado e as armas especiais."
    },
    {
        "title": "Gran Turismo 4",
        "genre": "Racing Simulation",
        "year": 2004,
        "developer": "Polyphony Digital",
        "publisher": "Sony Computer Entertainment",
        "rating": 89,
        "description": "Simulador de corrida realista com mais de 700 carros e 50 circuitos, incluindo pistas reais.",
        "characters": "N/A",
        "gameplay_mechanics": "Física realista, customização detalhada, B-Spec (modo gerenciamento)",
        "trivia": "O desenvolvimento levou mais de 3 anos, com cada carro sendo modelado com precisão extrema.",
        "tips_easter_eggs": "Use carros específicos para desbloquear eventos secretos como as corridas de Formula GT."
    },
    {
        "title": "Onimusha 3: Demon Siege",
        "genre": "Action-Adventure",
        "year": 2004,
        "developer": "Capcom",
        "publisher": "Capcom",
        "rating": 85,
        "description": "Samanosuke Akechi e o policial francês Jacques Blanc combatem demônios em duas épocas diferentes.",
        "characters": "Samanosuke Akechi, Jacques Blanc, Michelle Aubert, Ako",
        "gameplay_mechanics": "Sistema de absorção de almas, combate com espadas, mudança entre personagens",
        "trivia": "O ator francês Jean Reno emprestou sua aparência e voz para o personagem Jacques.",
        "tips_easter_eggs": "Durante a luta com Ranmaru, destrua os pilares da sala para causar dano extra."
    },
    {
        "title": "Tekken 5",
        "genre": "Fighting",
        "year": 2004,
        "developer": "Namco",
        "publisher": "Namco",
        "rating": 88,
        "description": "Torneio do Punho de Ferro após a dissolução da Mishima Zaibatsu, com novos personagens e mecânicas.",
        "characters": "Kazuya Mishima, Jin Kazama, Heihachi Mishima, e outros 30+ lutadores",
        "gameplay_mechanics": "Sistema de luta 3D, combos, arremessos técnicos",
        "trivia": "Inclui versões arcade completas de Tekken 1, 2 e 3 como bônus.",
        "tips_easter_eggs": "Complete o modo história com todos os personagens para desbloquear Jinpachi Mishima."
    },
    {
        "title": "Ratchet & Clank: Up Your Arsenal",
        "genre": "Platformer-Shooter",
        "year": 2004,
        "developer": "Insomniac Games",
        "publisher": "Sony Computer Entertainment",
        "rating": 91,
        "description": "Ratchet e Clank enfrentam o Dr. Nefarious que planeja transformar toda vida orgânica em robôs.",
        "characters": "Ratchet, Clank, Captain Qwark, Dr. Nefarious",
        "gameplay_mechanics": "Plataforma, armas bizarras e customizáveis, multiplayer",
        "trivia": "Primeiro jogo da série a incluir modo multiplayer online.",
        "tips_easter_eggs": "Encontre todos os Titanium Bolts para desbloquear filtros visuais especiais."
    },
    {
        "title": "Metal Gear Solid 2: Sons of Liberty",
        "genre": "Stealth",
        "year": 2001,
        "developer": "Konami",
        "publisher": "Konami",
        "rating": 96,
        "description": "Solid Snake e o novato Raiden enfrentam uma organização terrorista que sequestrou o presidente dos EUA.",
        "characters": "Solid Snake, Raiden, Otacon, Rose, Solidus Snake",
        "gameplay_mechanics": "Stealth aprimorado, perspectiva em primeira pessoa, ambiente interativo",
        "trivia": "Um dos primeiros jogos a abordar temas como fake news e controle da informação digital.",
        "tips_easter_eggs": "Tire fotos dos pôsteres em locais específicos para desbloquear extras."
    },
    {
        "title": "SSX Tricky",
        "genre": "Sports - Snowboarding",
        "year": 2001,
        "developer": "EA Canada",
        "publisher": "EA Sports BIG",
        "rating": 92,
        "description": "Competição de snowboarding com pistas exageradas, manobras impossíveis e personagens carismáticos.",
        "characters": "Mac, Kaori, Moby, Zoe, JP, e outros competidores",
        "gameplay_mechanics": "Sistema de truques Uber, combos, boost ilimitado com Tricky",
        "trivia": "Contou com vozes de celebridades como David Arquette e Macy Gray.",
        "tips_easter_eggs": "Use Kaori na pista Tokyo Megaplex para descobrir um atalho secreto."
    },
    {
        "title": "Black",
        "genre": "First-Person Shooter",
        "year": 2006,
        "developer": "Criterion Games",
        "publisher": "Electronic Arts",
        "rating": 80,
        "description": "Operativo Jack Kellar desvenda uma conspiração enquanto destrói praticamente tudo em seu caminho.",
        "characters": "Sergeant Jack Kellar, William Garrett, Lenox",
        "gameplay_mechanics": "Sistema de destruição ambiental, arsenal realista, ênfase em explosões",
        "trivia": "Desenvolvido pela mesma equipe de Burnout, mas com foco em destruição de cenários.",
        "tips_easter_eggs": "Atire nos carros vermelhos para causar explosões maiores e em cadeia."
    },
    {
        "title": "Bully",
        "genre": "Action-Adventure",
        "year": 2006,
        "developer": "Rockstar Vancouver",
        "publisher": "Rockstar Games",
        "rating": 87,
        "description": "Jimmy Hopkins navega a vida no internato Bullworth Academy, lidando com valentões e autoridades.",
        "characters": "Jimmy Hopkins, Gary Smith, Pete Kowalski, Dr. Crabblesnitch",
        "gameplay_mechanics": "Mundo aberto escolar, aulas como minigames, sistema de reputação",
        "trivia": "Originalmente chamado 'Canis Canem Edit' na Europa devido a controvérsias.",
        "tips_easter_eggs": "Complete todas as aulas de química para criar bombas de fedor ilimitadas."
    },
    {
        "title": "TimeSplitters 2",
        "genre": "First-Person Shooter",
        "year": 2002,
        "developer": "Free Radical Design",
        "publisher": "Eidos Interactive",
        "rating": 89,
        "description": "Os protagonistas viajam através de diferentes períodos históricos para impedir que alienígenas alterem o passado.",
        "characters": "Cortez, Hart, vários personagens específicos de cada época",
        "gameplay_mechanics": "FPS arcade, multiplayer split-screen, level editor",
        "trivia": "Criado por ex-membros da equipe de GoldenEye 007 e Perfect Dark.",
        "tips_easter_eggs": "No nível da Sibéria, derrote todos os soldados sem ser detectado para um final alternativo."
    },
    {
        "title": "Sly 2: Band of Thieves",
        "genre": "Platformer-Stealth",
        "year": 2004,
        "developer": "Sucker Punch Productions",
        "publisher": "Sony Computer Entertainment",
        "rating": 88,
        "description": "Sly Cooper e sua gangue precisam recuperar as partes da Clockwerk antes que a Klaww Gang as use para o mal.",
        "characters": "Sly Cooper, Bentley, Murray, Carmelita Fox",
        "gameplay_mechanics": "Stealth, personagens jogáveis diferentes, planejamento de assaltos",
        "trivia": "A arte foi inspirada em quadrinhos e animações cel-shaded.",
        "tips_easter_eggs": "Mantenha-se anônimo durante uma missão inteira para receber recompensas extras."
    },
    {
        "title": "God of War",
        "genre": "Hack and Slash",
        "year": 2005,
        "developer": "SCE Santa Monica Studio",
        "publisher": "Sony Computer Entertainment",
        "rating": 94,
        "description": "O espartano Kratos faz um pacto com Ares e depois busca vingança contra o Deus da Guerra que o enganou.",
        "characters": "Kratos, Ares, Athena, Zeus, Oráculo",
        "gameplay_mechanics": "Combate com correntes, quick time events, puzzles",
        "trivia": "David Jaffe criou o conceito enquanto assistia a documentários sobre mitologia grega.",
        "tips_easter_eggs": "Termine o jogo na dificuldade God para desbloquear trajes especiais."
    },
    {
        "title": "Katamari Damacy",
        "genre": "Puzzle-Action",
        "year": 2004,
        "developer": "Namco",
        "publisher": "Namco",
        "rating": 86,
        "description": "O Príncipe do Cosmos rola uma bola adesiva (katamari) que cresce à medida que coleta objetos para substituir as estrelas.",
        "characters": "Prince, King of All Cosmos, Queen",
        "gameplay_mechanics": "Rolar katamari para coletar objetos, tempo limitado, objetivos de tamanho",
        "trivia": "Foi criado com um orçamento baixo por uma pequena equipe como experimento.",
        "tips_easter_eggs": "Encontre a vaca arco-íris escondida na fase Make a Star 4 para pontos extras."
    },
    {
        "title": "Star Wars: Battlefront II",
        "genre": "Action-Shooter",
        "year": 2005,
        "developer": "Pandemic Studios",
        "publisher": "LucasArts",
        "rating": 84,
        "description": "Participe das maiores batalhas da série Star Wars como soldado, piloto ou jedi em diferentes eras.",
        "characters": "Soldados de facções diversas, Jedi e Sith jogáveis",
        "gameplay_mechanics": "Combate em terceira pessoa, multiplayer em larga escala, naves espaciais",
        "trivia": "Inclui missões da operação 501 que se conectam aos eventos do Episódio III.",
        "tips_easter_eggs": "Acumule pontos suficientes em uma partida para jogar como Darth Vader ou Luke Skywalker."
    },
    {
        "title": "Xenosaga Episode I: Der Wille zur Macht",
        "genre": "RPG",
        "year": 2002,
        "developer": "Monolith Soft",
        "publisher": "Namco",
        "rating": 83,
        "description": "Shion Uzuki e seus aliados combatem uma ameaça alienígena enquanto investigam artefatos antigos em uma aventura espacial.",
        "characters": "Shion Uzuki, KOS-MOS, chaos, Jr., MOMO",
        "gameplay_mechanics": "Combate por turnos, Tech/Ether/Skill points, A.G.W.S. mechs",
        "trivia": "Parte de uma série planejada de seis jogos, mas apenas três foram concluídos.",
        "tips_easter_eggs": "Desbloqueie o minigame de cartas colecionáveis para ganhar itens raros."
    },
    {
        "title": "Gradius V",
        "genre": "Shoot 'em Up",
        "year": 2004,
        "developer": "Treasure",
        "publisher": "Konami",
        "rating": 87,
        "description": "O lendário caça Vic Viper retorna para enfrentar uma nova ameaça da armada Bacterian em um shooter clássico.",
        "characters": "N/A",
        "gameplay_mechanics": "Sistema de power-ups, opções de tiro, múltiplos tipos de nave",
        "trivia": "Desenvolvido pela Treasure, famosa por shooters como Ikaruga e Radiant Silvergun.",
        "tips_easter_eggs": "Selecione rapidamente opções específicas na tela de título para acessar naves secretas."
    },
    {
        "title": "The Warriors",
        "genre": "Beat 'em up",
        "year": 2005,
        "developer": "Rockstar Toronto",
        "publisher": "Rockstar Games",
        "rating": 84,
        "description": "Baseado no filme de 1979, acompanha a gangue Warriors tentando retornar ao seu território após serem acusados de assassinato.",
        "characters": "Swan, Ajax, Cleon, Cochise, outros membros dos Warriors",
        "gameplay_mechanics": "Combate corpo a corpo, gerenciamento de gangue, furtividade",
        "trivia": "Walter Hill, diretor do filme original, trabalhou como consultor no jogo.",
        "tips_easter_eggs": "No esconderijo da gangue, procure por desafios especiais que desbloqueiam conteúdo extra."
    },
    {
        "title": "Final Fantasy XII",
        "genre": "RPG",
        "year": 2006,
        "developer": "Square Enix",
        "publisher": "Square Enix",
        "rating": 92,
        "description": "No mundo de Ivalice, Vaan e aliados se envolvem em uma guerra política entre impérios enquanto descobrem segredos antigos.",
        "characters": "Vaan, Ashe, Balthier, Fran, Basch, Penelo",
        "gameplay_mechanics": "Sistema de batalha em tempo real, Gambit System, License Board",
        "trivia": "Foi dirigido por Yasumi Matsuno, criador de Final Fantasy Tactics, até seu afastamento por problemas de saúde.",
        "tips_easter_eggs": "Cace todos os monstros da Clan Primer para desbloquear recompensas especiais."
    },
    {
        "title": "Ace Combat 04: Shattered Skies",
        "genre": "Combat Flight Simulator",
        "year": 2001,
        "developer": "Namco",
        "publisher": "Namco",
        "rating": 89,
        "description": "Piloto com codinome Mobius 1 combate as forças de Erusea em uma guerra fictícia com aeronaves baseadas em modelos reais.",
        "characters": "Mobius 1, Yellow 13, diversos personagens de suporte",
        "gameplay_mechanics": "Simulação de voo acessível, campanha com narrativa, variedade de aeronaves",
        "trivia": "Primeiro jogo da série no PS2 e considerado um marco para a franquia.",
        "tips_easter_eggs": "Complete a campanha com ranking S para desbloquear a aeronave experimental X-02 Wyvern."
    },
    {
        "title": "Psychonauts",
        "genre": "Platformer",
        "year": 2005,
        "developer": "Double Fine Productions",
        "publisher": "Majesco Entertainment",
        "rating": 87,
        "description": "Raz, um garoto com poderes psíquicos, infiltra-se em um acampamento para agentes psíquicos e descobre uma conspiração.",
        "characters": "Razputin, Sasha Nein, Milla Vodello, Coach Oleander",
        "gameplay_mechanics": "Plataforma 3D, poderes psíquicos diversos, exploração mental",
        "trivia": "Primeiro jogo de Tim Schafer após deixar a LucasArts, foi um fracasso comercial inicial.",
        "tips_easter_eggs": "Dentro da mente de Boyd, descubra as pistas ocultas para resolver o mistério do incêndio."
    },
    {
        "title": "Suikoden III",
        "genre": "RPG",
        "year": 2002,
        "developer": "Konami",
        "publisher": "Konami",
        "rating": 86,
        "description": "Três protagonistas encontram-se em lados opostos de um conflito, cada um com sua perspectiva dos eventos.",
        "characters": "Hugo, Chris Lightfellow, Geddoe, dezenas de personagens recrutáveis",
        "gameplay_mechanics": "Sistema Trinity Sight, 108 Stars of Destiny, batalhas estratégicas",
        "trivia": "Primeiro Suikoden com gráficos 3D e o último com participação direta do criador da série.",
        "tips_easter_eggs": "Recrute todos os 108 Stars of Destiny para desbloquear o final verdadeiro."
    },
    {
        "title": "Shin Megami Tensei: Nocturne",
        "genre": "RPG",
        "year": 2003,
        "developer": "Atlus",
        "publisher": "Atlus",
        "rating": 82,
        "description": "Após o Apocalipse, o protagonista é transformado em um meio-demônio e deve escolher como remodelar o mundo.",
        "characters": "Demi-fiend, Chiaki, Isamu, Hikawa, Lucifer",
        "gameplay_mechanics": "Press Turn battle system, negociação com demônios, fusão de demônios",
        "trivia": "Inclui Dante de Devil May Cry como personagem jogável na versão Maniax.",
        "tips_easter_eggs": "Complete todos os calabouços Kalpas para enfrentar o chefe mais difícil do jogo."
    },
    {
        "title": "Spider-Man 2",
        "genre": "Action-Adventure",
        "year": 2004,
        "developer": "Treyarch",
        "publisher": "Activision",
        "rating": 80,
        "description": "Baseado no filme, Peter Parker balanceia sua vida pessoal com a responsabilidade de ser o Homem-Aranha.",
        "characters": "Spider-Man/Peter Parker, Doctor Octopus, Black Cat, Harry Osborn",
        "gameplay_mechanics": "Balanço livre pela cidade, combate ágil, missões secundárias",
        "trivia": "Considerado revolucionário por seu sistema de balanço e mundo aberto para a época.",
        "tips_easter_eggs": "Complete todas as missões de pizza entregando no tempo para desbloquear trajes alternativos."
    },
    {
        "title": "Beyond Good & Evil",
        "genre": "Action-Adventure",
        "year": 2003,
        "developer": "Ubisoft Montpellier",
        "publisher": "Ubisoft",
        "rating": 87,
        "description": "A fotógrafa Jade investiga uma conspiração alienígena que ameaça seu planeta.",
        "characters": "Jade, Pey'j, Double H, Secundo",
        "gameplay_mechanics": "Fotografia como mecânica principal, combate, stealth, quebra-cabeças",
        "trivia": "Fracasso comercial inicial, mas tornou-se um cult classic com sequência anunciada anos depois.",
        "tips_easter_eggs": "Fotografe todas as espécies de animais para desbloquear upgrades especiais."
    },
    {
        "title": "Viewtiful Joe",
        "genre": "Beat 'em up",
        "year": 2003,
        "developer": "Capcom",
        "publisher": "Capcom",
        "rating": 93,
        "description": "Joe é transportado para dentro de um filme e ganha poderes para resgatar sua namorada.",
        "characters": "Joe, Silvia, Captain Blue, Alastor",
        "gameplay_mechanics": "VFX Powers (slow motion, mach speed, zoom), combos, estilo side-scrolling",
        "trivia": "Dirigido por Hideki Kamiya, criador de Devil May Cry e Bayonetta.",
        "tips_easter_eggs": "Use slow + zoom em determinados inimigos para descobrir ataques especiais."
    },
    {
        "title": "Disgaea: Hour of Darkness",
        "genre": "Tactical RPG",
        "year": 2003,
        "developer": "Nippon Ichi",
        "publisher": "Atlus",
        "rating": 84,
        "description": "Laharl, filho do Rei dos Demônios, desperta após dois anos e tenta reconquistar seu trono.",
        "characters": "Laharl, Etna, Flonne, Mid-Boss",
        "gameplay_mechanics": "Combate tático por turnos, Item World, Geo Panels, level cap até 9999",
        "trivia": "O jogo é conhecido por seu humor único e sistemas que permitem power leveling extremo.",
        "tips_easter_eggs": "No capítulo 3, levante Laharl 10 vezes para desbloquear uma cena secreta com Etna."
    },
    {
        "title": "Jak and Daxter: The Precursor Legacy",
        "genre": "Platformer",
        "year": 2001,
        "developer": "Naughty Dog",
        "publisher": "Sony Computer Entertainment",
        "rating": 90,
        "description": "Jak e seu amigo transformado em doninha, Daxter, exploram um mundo para reverter a transformação e deter Gol e Maia.",
        "characters": "Jak, Daxter, Samos, Keira",
        "gameplay_mechanics": "Plataforma 3D, coleta de Power Cells, mundo sem telas de carregamento",
        "trivia": "Primeiro grande título do PS2 da Naughty Dog, depois de Crash Bandicoot.",
        "tips_easter_eggs": "Colete todos os orbes de energia para desbloquear o final estendido."
    },
    {
        "title": "Twisted Metal: Black",
        "genre": "Vehicular Combat",
        "year": 2001,
        "developer": "Incognito Entertainment",
        "publisher": "Sony Computer Entertainment",
        "rating": 91,
        "description": "Competidores com veículos armados participam do torneio Twisted Metal organizado por Calypso.",
        "characters": "Sweet Tooth, Dollface, Mr. Grimm, outros pilotos",
        "gameplay_mechanics": "Combate veicular, armas especiais únicas para cada veículo",
        "trivia": "Tom de história muito mais sombrio que os jogos anteriores da série.",
        "tips_easter_eggs": "Na arena Snowy Roads, derrube todos os bonecos de neve para desbloquear o carro Minion."
    },
    {
        "title": "Need for Speed: Underground 2",
        "genre": "Racing",
        "year": 2004,
        "developer": "EA Black Box",
        "publisher": "Electronic Arts",
        "rating": 82,
        "description": "Corridas ilegais de rua em mundo aberto com amplas opções de personalização de veículos.",
        "characters": "N/A",
        "gameplay_mechanics": "Customização detalhada, mundo aberto, diferentes modos de corrida",
        "trivia": "Introduziu a exploração livre em mundo aberto na série Need for Speed.",
        "tips_easter_eggs": "Dirija para o aeroporto à noite para encontrar corridas secretas com recompensas únicas."
    },
    {
        "title": "Zone of the Enders: The 2nd Runner",
        "genre": "Action Mecha",
        "year": 2003,
        "developer": "Konami",
        "publisher": "Konami",
        "rating": 82,
        "description": "Dingo Egret encontra o mecha Jehuty e luta contra as forças BAHRAM em uma batalha pelo controle de Marte.",
        "characters": "Dingo Egret, Ken Marinaris, Nohman, ADA",
        "gameplay_mechanics": "Combate de mecha em alta velocidade, armas de energia, ataques especiais",
        "trivia": "Produzido por Hideo Kojima como um projeto paralelo a Metal Gear Solid.",
        "tips_easter_eggs": "Colete todos os Zoradias escondidos para desbloquear o modo Versus completo."
    },
    {
        "title": "Amplitude",
        "genre": "Rhythm",
        "year": 2003,
        "developer": "Harmonix",
        "publisher": "Sony Computer Entertainment",
        "rating": 84,
        "description": "Jogo musical onde o jogador pilota uma nave e ativa notas em diferentes pistas para compor músicas.",
        "characters": "N/A",
        "gameplay_mechanics": "Ativação de múltiplas pistas musicais, power-ups, multiplayer",
        "trivia": "Precursor de Guitar Hero e Rock Band, também da Harmonix.",
        "tips_easter_eggs": "Jogue na dificuldade insano para desbloquear músicas secretas e remixes."
    },
    {
        "title": "Mercenaries: Playground of Destruction",
        "genre": "Action-Adventure",
        "year": 2005,
        "developer": "Pandemic Studios",
        "publisher": "LucasArts",
        "rating": 84,
        "description": "Um mercenário trabalha para diversas facções na Coreia do Norte durante uma guerra civil.",
        "characters": "Chris Jacobs, Jennifer Mui, Mattias Nilsson",
        "gameplay_mechanics": "Mundo aberto destrutível, veículos, suporte aéreo, diferentes facções",
        "trivia": "Um dos primeiros jogos com ambientes quase completamente destrutíveis.",
        "tips_easter_eggs": "Use o código 'Bomber' para ter acesso a bombardeios aéreos ilimitados."
    },
    {
        "title": "Rogue Galaxy",
        "genre": "Action RPG",
        "year": 2005,
        "developer": "Level-5",
        "publisher": "Sony Computer Entertainment",
        "rating": 85,
        "description": "Jaster Rogue é confundido com um lendário caçador de recompensas e se junta a piratas espaciais em uma aventura pela galáxia.",
        "characters": "Jaster Rogue, Simon, Lilika, Steve",
        "gameplay_mechanics": "Combate em tempo real, Factory System para criação de itens, Revelation Flow",
        "trivia": "Um dos últimos grandes RPGs exclusivos do PS2.",
        "tips_easter_eggs": "Complete todas as caçadas do Hunter's Guild para desbloquear armas lendárias."
    },
    {
        "title": "Baldur's Gate: Dark Alliance",
        "genre": "Action RPG",
        "year": 2001,
        "developer": "Snowblind Studios",
        "publisher": "Black Isle Studios",
        "rating": 87,
        "description": "Três aventureiros combatem uma conspiração que ameaça a cidade de Baldur's Gate, ambientado no universo de Dungeons & Dragons.",
        "characters": "Vahn, Kromlech, Adrianna",
        "gameplay_mechanics": "Hack and slash com elementos de RPG, customização de equipamentos, cooperativo",
        "trivia": "Adaptação da série Baldur's Gate para consoles com foco em ação.",
        "tips_easter_eggs": "Encontre as 9 estátuas escondidas para obter a arma mais poderosa do jogo."
    },
    {
        "title": "Fatal Frame II: Crimson Butterfly",
        "genre": "Survival Horror",
        "year": 2003,
        "developer": "Tecmo",
        "publisher": "Tecmo",
        "rating": 85,
        "description": "Gêmeas Mio e Mayu encontram uma vila abandonada habitada por fantasmas que só podem ser derrotados com uma câmera especial.",
        "characters": "Mio Amakura, Mayu Amakura, vários fantasmas com histórias próprias",
        "gameplay_mechanics": "Camera Obscura para combater fantasmas, exploração, puzzles",
        "trivia": "Baseado em lendas japonesas reais sobre sacrifícios de gêmeos.",
        "tips_easter_eggs": "Fotografe fantasmas em ângulos específicos para maximizar o dano com a câmera."
    },
    {
        "title": "NBA Street Vol. 2",
        "genre": "Sports",
        "year": 2003,
        "developer": "EA Canada",
        "publisher": "EA Sports BIG",
        "rating": 89,
        "description": "Basquete de rua com jogadores da NBA e lendas em quadras urbanas com jogabilidade arcade.",
        "characters": "Jogadores da NBA como Allen Iverson, Michael Jordan, e personagens originais",
        "gameplay_mechanics": "Sistema de truques, Gamebreakers, 3x3 com movimentos exagerados",
        "trivia": "Primeiro jogo a incluir Michael Jordan, Dr. J e Magic Johnson juntos.",
        "tips_easter_eggs": "Vença todos os torneios para desbloquear a quadra secreta de Rucker Park."
    },
    {
        "title": "War of the Monsters",
        "genre": "Fighting",
        "year": 2003,
        "developer": "Incognito Entertainment",
        "publisher": "Sony Computer Entertainment",
        "rating": 82,
        "description": "Monstros gigantes inspirados em filmes clássicos de Kaiju lutam em cidades destrutíveis.",
        "characters": "Congar (King Kong), Togera (Godzilla), Robo-47 (robôs gigantes)",
        "gameplay_mechanics": "Arenas destrutíveis, armas ambientais, combate em 3D livre",
        "trivia": "Homenageia filmes de monstros dos anos 50-60 com estética correspondente.",
        "tips_easter_eggs": "Na fase do parque de diversões, derrube a montanha-russa para criar um novo caminho."
    },
    {
        "title": "Soulcalibur II",
        "genre": "Fighting",
        "year": 2003,
        "developer": "Project Soul",
        "publisher": "Namco",
        "rating": 91,
        "description": "Guerreiros de diferentes origens buscam a lendária espada Soul Edge em um torneio de combate com armas.",
        "characters": "Mitsurugi, Ivy, Nightmare, Kilik, Heihachi (exclusivo do PS2)",
        "gameplay_mechanics": "Combate com armas em arenas 3D, Guard Impact, movimentos especiais",
        "trivia": "Cada versão de console tinha um personagem convidado exclusivo.",
        "tips_easter_eggs": "Complete o modo Weapon Master para desbloquear todos os trajes alternativos."
    },
    {
        "title": "Manhunt",
        "genre": "Stealth Horror",
        "year": 2003,
        "developer": "Rockstar North",
        "publisher": "Rockstar Games",
        "rating": 76,
        "description": "James Earl Cash é forçado a participar de um 'filme' snuff dirigido por um diretor psicopata, eliminando gangues violentas.",
        "characters": "James Earl Cash, Diretor Starkweather, Piggsy",
        "gameplay_mechanics": "Stealth, execuções brutais, classificação por nível de violência",
        "trivia": "Um dos jogos mais controversos da história devido à violência gráfica.",
        "tips_easter_eggs": "Obtenha classificação 5 estrelas em todas as fases para desbloquear conteúdos extras."
    },
    {
        "title": "Radiata Stories",
        "genre": "RPG",
        "year": 2005,
        "developer": "tri-Ace",
        "publisher": "Square Enix",
        "rating": 76,
        "description": "Jack Russell, um jovem cavaleiro, encontra-se no meio de uma guerra entre humanos e fadas.",
        "characters": "Jack Russell, Ridley Silverlake, Ganz Rothschild",
        "gameplay_mechanics": "Combate em tempo real, recrutamento de 176 personagens, ciclo de dia e noite",
        "trivia": "O jogo permite chutar praticamente tudo, incluindo pessoas, para interagir com o ambiente.",
        "tips_easter_eggs": "Siga personagens específicos durante o dia para descobrir side quests secretas."
    },
    {
        "title": "SOCOM II: U.S. Navy SEALs",
        "genre": "Tactical Shooter",
        "year": 2003,
        "developer": "Zipper Interactive",
        "publisher": "Sony Computer Entertainment",
        "rating": 87,
        "description": "Comandando uma equipe de Navy SEALs, o jogador participa de operações militares táticas ao redor do mundo.",
        "characters": "SEAL Fireteam (Boomer, Jester, Spectre), antagonistas variados",
        "gameplay_mechanics": "Controle tático, comandos de voz com headset, multijogador online",
        "trivia": "Um dos primeiros grandes sucessos de multiplayer online do PS2.",
        "tips_easter_eggs": "Use o headset para dar ordens específicas que não estão disponíveis no menu de comandos."
    },
    {
        "title": "Mark of Kri",
        "genre": "Action-Adventure",
        "year": 2002,
        "developer": "SCE San Diego Studio",
        "publisher": "Sony Computer Entertainment",
        "rating": 84,
        "description": "Rau, um poderoso guerreiro com um pássaro guia, enfrenta uma antiga maldição e cultistas perigosos.",
        "characters": "Rau Utu, Kuzo (pássaro), Tati",
        "gameplay_mechanics": "Sistema de combate com múltiplos inimigos usando o analógico direito, stealth",
        "trivia": "A arte do jogo foi inspirada em animações da Disney, apesar do conteúdo violento.",
        "tips_easter_eggs": "Encontre todos os totens escondidos para aumentar permanentemente sua saúde máxima."
    },
    {
        "title": "Soul Calibur III",
        "genre": "Fighting",
        "year": 2005,
        "developer": "Project Soul",
        "publisher": "Namco",
        "rating": 86,
        "description": "Continuação da saga da espada Soul Edge, com novos personagens e história expandida.",
        "characters": "Mitsurugi, Ivy, Nightmare, Kilik, Tira, Zasalamel",
        "gameplay_mechanics": "Combate com armas, sistema de criação de personagens, modos Chronicles of the Sword e Tales of Souls",
        "trivia": "Primeiro jogo da série a incluir um criador de personagens detalhado.",
        "tips_easter_eggs": "Complete o modo Chronicles of the Sword para desbloquear partes de equipamento raras."
    },
    {
        "title": "Gitaroo Man",
        "genre": "Rhythm",
        "year": 2001,
        "developer": "iNiS",
        "publisher": "Koei",
        "rating": 80,
        "description": "U-1, um garoto tímido, descobre que é o lendário Gitaroo Man e deve defender a Terra com sua guitarra mágica.",
        "characters": "U-1/Gitaroo Man, Puma, Kirah, vários chefes musicais",
        "gameplay_mechanics": "Controle de traços de guitarra, seções de defesa e ataque",
        "trivia": "Cult classic com trilha sonora que mistura diversos gêneros musicais.",
        "tips_easter_eggs": "Complete o jogo na dificuldade Masters para desbloquear a música secreta 'Legendary Theme'."
    },
    {
        "title": "Front Mission 4",
        "genre": "Tactical RPG",
        "year": 2003,
        "developer": "Square Enix",
        "publisher": "Square Enix",
        "rating": 74,
        "description": "Em um futuro alternativo, conflitos geopolíticos são resolvidos com batalhas de mechas chamados Wanzers.",
        "characters": "Elsa, Darril, Billy, Hermes",
        "gameplay_mechanics": "Combate tático por turnos, customização detalhada de Wanzers, ataques linkados",
        "trivia": "Foi o primeiro jogo da série a ser completamente ambientado na Europa e América do Sul.",
        "tips_easter_eggs": "Personalize seus Wanzers com equilíbrio entre peso e poder de fogo para maior eficiência."
    },
    {
        "title": "Dark Cloud 2",
        "genre": "Action RPG",
        "year": 2002,
        "developer": "Level-5",
        "publisher": "Sony Computer Entertainment",
        "rating": 87,
        "description": "Max e Monica viajam entre presente e futuro para impedir que o maligno Imperador Griffin altere a história.",
        "characters": "Max, Monica, Cedric, Flotsam",
        "gameplay_mechanics": "Dungeon crawling, Georama (construção de cidades), invenções, pesca, golfe",
        "trivia": "Conhecido como Dark Chronicle na Europa e Japão.",
        "tips_easter_eggs": "Use a câmera para fotografar todos os objetos do mundo e completar suas ideias de invenção."
    },
    {
        "title": "Klonoa 2: Lunatea's Veil",
        "genre": "Platformer",
        "year": 2001,
        "developer": "Namco",
        "publisher": "Namco",
        "rating": 91,
        "description": "Klonoa é transportado para o mundo de Lunatea, onde deve restaurar o equilíbrio usando seu anel Wind Bullet.",
        "characters": "Klonoa, Lolo, Popka, Leorina",
        "gameplay_mechanics": "Plataforma 2.5D, Wind Bullet para pegar inimigos, voo controlado",
        "trivia": "A misteriosa língua falada no jogo é na verdade japonês tocado de trás para frente.",
        "tips_easter_eggs": "Colete todos os Momett Dolls em cada nível para desbloquear áreas secretas."
    },
    {
        "title": "Def Jam: Fight for NY",
        "genre": "Fighting",
        "year": 2004,
        "developer": "EA Chicago",
        "publisher": "EA Games",
        "rating": 84,
        "description": "Lutador de rua personalizado enfrenta gangues em Nova York, com rappers reais como Snoop Dogg e Method Man.",
        "characters": "D-Mob, Snoop Dogg, Method Man, Redman, outros rappers",
        "gameplay_mechanics": "Combate em ambientes interativos, diferentes estilos de luta, personalização de personagem",
        "trivia": "Mais de 40 artistas da Def Jam Records aparecem como personagens.",
        "tips_easter_eggs": "Foque em um único estilo de luta para maximizar sua eficiência em torneios."
    },
    {
        "title": "Wild Arms 3",
        "genre": "RPG",
        "year": 2002,
        "developer": "Media.Vision",
        "publisher": "Sony Computer Entertainment",
        "rating": 82,
        "description": "Quatro Drifters buscam fortuna no planeta Filgaia, um mundo em estilo Velho Oeste com tecnologia e magia.",
        "characters": "Virginia Maxwell, Jet Enduro, Clive Winslett, Gallows Caradine",
        "gameplay_mechanics": "Combate por turnos, puzzles com ferramentas, sistema de ADV (armas mágicas)",
        "trivia": "Primeiro jogo da série com gráficos cel-shaded em estilo anime.",
        "tips_easter_eggs": "No início do jogo, selecione 'chaotic' quando perguntado sobre sua vida para ganhar itens raros."
    },
    {
        "title": "Haunting Ground",
        "genre": "Survival Horror",
        "year": 2005,
        "developer": "Capcom",
        "publisher": "Capcom",
        "rating": 67,
        "description": "Fiona Belli acorda em um castelo misterioso após um acidente e, com a ajuda de um cão chamado Hewie, tenta escapar de seus perseguidores.",
        "characters": "Fiona Belli, Hewie, Debilitas, Daniella, Riccardo",
        "gameplay_mechanics": "Evasão, esconderijos, comandos para o cão, sistema de pânico",
        "trivia": "Considerado um sucessor espiritual de Clock Tower, com ênfase em fuga em vez de combate.",
        "tips_easter_eggs": "Trate bem o Hewie e recompense-o frequentemente para melhorar sua resposta aos comandos."
    },
    {
        "title": "Maximo: Ghosts to Glory",
        "genre": "Action-Adventure",
        "year": 2001,
        "developer": "Capcom",
        "publisher": "Capcom",
        "rating": 84,
        "description": "Inspirado em Ghosts 'n Goblins, o cavaleiro Maximo deve derrotar o feiticeiro Achille que roubou seu reino e sua noiva.",
        "characters": "Maximo, Grim Reaper, Achille, Sophia",
        "gameplay_mechanics": "Plataforma 3D com combate de espada, armaduras que se despedaçam com danos",
        "trivia": "Projetado como uma reinvenção 3D do clássico Ghosts 'n Goblins.",
        "tips_easter_eggs": "Gaste moedas com o Grim Reaper para garantir continues adicionais."
    },
    {
        "title": "Raw Danger!",
        "genre": "Survival Adventure",
        "year": 2006,
        "developer": "Irem",
        "publisher": "Agetec",
        "rating": 71,
        "description": "Durante uma inundação catastrófica, seis personagens tentam sobreviver enquanto descobrem uma conspiração por trás do desastre.",
        "characters": "Joshua Harwell, Amber Brazil, outros 4 protagonistas jogáveis",
        "gameplay_mechanics": "Sobrevivência, gerenciamento de temperatura corporal, múltiplas rotas de história",
        "trivia": "Sequência espiritual de Disaster Report, com ênfase em escolhas que afetam a narrativa.",
        "tips_easter_eggs": "Mantenha-se seco e aquecido durante tempestades para evitar hipotermia."
    },
    {
        "title": "Dark Cloud",
        "genre": "Action RPG",
        "year": 2000,
        "developer": "Level-5",
        "publisher": "Sony Computer Entertainment",
        "rating": 80,
        "description": "Toan recebe a Atlamillia, uma pedra mágica que pode restaurar o mundo após sua destruição pelo Gênio Negro.",
        "characters": "Toan, Xiao, Goro, Ruby, Ungaga, Osmond",
        "gameplay_mechanics": "Dungeon crawling, Georama (reconstrução de vilas), armas com atributos únicos",
        "trivia": "Primeiro jogo desenvolvido pela Level-5, que depois criou séries como Professor Layton.",
        "tips_easter_eggs": "Mantenha suas armas reparadas pois elas podem quebrar permanentemente se a durabilidade chegar a zero."
    },
    {
        "title": "Shadow Hearts",
        "genre": "RPG",
        "year": 2001,
        "developer": "Sacnoth",
        "publisher": "Midway",
        "rating": 85,
        "description": "Em uma versão alternativa de 1913, Yuri Hyuga, um harmonixer que pode se transformar em monstros, luta contra forças sobrenaturais.",
        "characters": "Yuri Hyuga, Alice Elliot, Zhuzhen, Margarete",
        "gameplay_mechanics": "Judgment Ring para ações, fusões com monstros, ambientação de horror",
        "trivia": "Sucessor espiritual de Koudelka do PlayStation 1, misturando RPG e horror.",
        "tips_easter_eggs": "Para aumentar suas chances no Judgment Ring, procure por itens que expandem as áreas de acerto."
    },
    {
        "title": "Final Fantasy X-2",
        "genre": "RPG",
        "year": 2003,
        "developer": "Square",
        "publisher": "Square",
        "rating": 85,
        "description": "Dois anos após Final Fantasy X, Yuna se torna uma caçadora de esferas e busca pistas sobre o paradeiro de Tidus.",
        "characters": "Yuna, Rikku, Paine, Leblanc, Nooj",
        "gameplay_mechanics": "Sistema de Garment Grid, missões não-lineares, múltiplos finais",
        "trivia": "Primeira sequência direta numerada na história da série Final Fantasy.",
        "tips_easter_eggs": "Complete 100% do jogo para ver o final secreto com o retorno de Tidus."
    },
    {
        "title": "Dirge of Cerberus: Final Fantasy VII",
        "genre": "Third-Person Shooter",
        "year": 2006,
        "developer": "Square Enix",
        "publisher": "Square Enix",
        "rating": 57,
        "description": "Vincent Valentine combate a misteriosa organização Deepground que ameaça o planeta três anos após os eventos de FFVII.",
        "characters": "Vincent Valentine, Yuffie, Shelke, Weiss, Nero",
        "gameplay_mechanics": "Tiro em terceira pessoa, customização de armas, elementos de RPG",
        "trivia": "Parte da Compilation of Final Fantasy VII, que expandiu o universo do jogo original.",
        "tips_easter_eggs": "Colete telefones móveis escondidos para desbloquear conteúdo extra e armas poderosas."
    },
    {
        "title": "Breath of Fire: Dragon Quarter",
        "genre": "RPG",
        "year": 2002,
        "developer": "Capcom",
        "publisher": "Capcom",
        "rating": 83,
        "description": "Em um mundo subterrâneo pós-apocalíptico, Ryu deve escolher entre usar poderes de dragão perigosos ou salvar uma garota misteriosa.",
        "characters": "Ryu, Nina, Lin, Bosch",
        "gameplay_mechanics": "Sistema SOL (cenário reiniciável), medidor D-Counter, combate tático",
        "trivia": "Radical mudança na série, extremamente diferente dos jogos anteriores tanto em história quanto em mecânicas.",
        "tips_easter_eggs": "Após terminar o jogo uma vez, reinicie o Scenario Overlay para desbloquear cenas extras."
    },
    {
        "title": "Bloody Roar 3",
        "genre": "Fighting",
        "year": 2000,
        "developer": "Eighting",
        "publisher": "Hudson Soft",
        "rating": 79,
        "description": "Lutadores com a habilidade de se transformar em animais (Zoanthropes) competem em um torneio global.",
        "characters": "Yugo, Alice, Long, Uriko, e outros zoanthropes",
        "gameplay_mechanics": "Sistema de transformação Beast Mode, arenas com paredes, ataques especiais",
        "trivia": "A série Bloody Roar foi uma das primeiras a utilizar o conceito de transformação durante combates.",
        "tips_easter_eggs": "Mantenha seu medidor Beast cheio para executar o devastador Beast Drive."
    },
    {
        "title": "Dynasty Warriors 5",
        "genre": "Hack and Slash",
        "year": 2005,
        "developer": "Omega Force",
        "publisher": "Koei",
        "rating": 78,
        "description": "Baseado no Romance dos Três Reinos, permite controlar generais históricos em batalhas massivas durante a guerra civil chinesa.",
        "characters": "Cao Cao, Liu Bei, Sun Jian, Lu Bu, dezenas de outros generais",
        "gameplay_mechanics": "Combate um contra centenas, Musou Attacks, modos de história para cada reino",
        "trivia": "A série é conhecida por exagerar feitos históricos, transformando generais em super-humanos.",
        "tips_easter_eggs": "Complete o modo Musou de todos os personagens para desbloquear modos de jogo adicionais."
    },
    {
        "title": "Armored Core 3",
        "genre": "Mecha Simulation",
        "year": 2002,
        "developer": "FromSoftware",
        "publisher": "Agetec",
        "rating": 81,
        "description": "Como piloto mercenário, o jogador customiza seu mecha (AC) para completar missões de várias corporações em guerra.",
        "characters": "NINEBALL, vários operadores de missão",
        "gameplay_mechanics": "Customização detalhada de mechas, economia de energia e munição, testes de arena",
        "trivia": "Desenvolvido pela FromSoftware, que mais tarde criaria a série Dark Souls.",
        "tips_easter_eggs": "Equilibre peso e mobilidade em seu AC para sobreviver a missões mais difíceis."
    },
    {
        "title": "Monster Hunter",
        "genre": "Action RPG",
        "year": 2004,
        "developer": "Capcom",
        "publisher": "Capcom",
        "rating": 71,
        "description": "Caçadores enfrentam monstros gigantes para coletar materiais e criar equipamentos melhores, em um ciclo de caça-coleta-criação.",
        "characters": "Caçadores customizáveis, vários NPCs de vila",
        "gameplay_mechanics": "Caça de monstros, sistema de dano por área, coleta de recursos",
        "trivia": "Primeiro jogo da franquia que se tornaria uma das mais lucrativas da Capcom.",
        "tips_easter_eggs": "Aprenda os padrões de ataque dos monstros antes de enfrentá-los diretamente."
    },
    {
        "title": "Ape Escape 3",
        "genre": "Platformer",
        "year": 2005,
        "developer": "SCE Japan Studio",
        "publisher": "Sony Computer Entertainment",
        "rating": 82,
        "description": "Kei e Yumi devem capturar macacos que escaparam e estão causando problemas em vários cenários de TV.",
        "characters": "Kei, Yumi, Professor, Specter, Jimmy",
        "gameplay_mechanics": "Transformações de personagem, gadgets especiais, captura de macacos",
        "trivia": "Inclui paródias de filmes e programas de TV populares da época.",
        "tips_easter_eggs": "Capture todos os macacos para desbloquear minigames especiais."
    },
    {
        "title": "Front Mission 3",
        "genre": "Tactical RPG",
        "year": 1999,
        "developer": "Square",
        "publisher": "Square",
        "rating": 81,
        "description": "Em um futuro alternativo, conflitos internacionais são resolvidos com Wanzers, mechas de combate pilotados.",
        "characters": "Kazuki Takemura, Ryogo Kusama, Alisa Takemura",
        "gameplay_mechanics": "Combate tático por turnos, customização de Wanzers, ataques especiais",
        "trivia": "O jogo tem duas campanhas completamente diferentes dependendo de uma escolha feita no início.",
        "tips_easter_eggs": "No início, escolha 'ir com Emma' ou 'ficar com Ryogo' para experimentar campanhas diferentes."
    },
    {
        "title": "XIII",
        "genre": "First-Person Shooter",
        "year": 2003,
        "developer": "Ubisoft Paris",
        "publisher": "Ubisoft",
        "rating": 74,
        "description": "Baseado em uma HQ belga, um homem com amnésia identificado apenas como 'XIII' tenta descobrir seu passado e envolvimento em uma conspiração.",
        "characters": "XIII, General Carrington, Mangusta, The Mongoose",
        "gameplay_mechanics": "FPS com estilo cel-shaded, sistema de stealth, armas variadas",
        "trivia": "O visual único imita quadrinhos, com onomatopeias e painéis durante o gameplay.",
        "tips_easter_eggs": "Use armas silenciosas como a besta para eliminar inimigos discretamente."
    },
    {
        "title": "Urban Chaos: Riot Response",
        "genre": "First-Person Shooter",
        "year": 2006,
        "developer": "Rocksteady Studios",
        "publisher": "Eidos Interactive",
        "rating": 72,
        "description": "Como oficial Nick Mason da unidade T-Zero, o jogador combate uma gangue chamada Burners em uma cidade dominada pela violência.",
        "characters": "Nick Mason, Kwan Chang, Morello",
        "gameplay_mechanics": "Sistema de escudo tático, resgate de civis, cooperação com bombeiros e paramédicos",
        "trivia": "Desenvolvido pela Rocksteady antes de eles criarem a série Batman: Arkham.",
        "tips_easter_eggs": "Use seu escudo para avançar contra inimigos armados e proteger reféns."
    },
    {
        "title": "Legacy of Kain: Soul Reaver 2",
        "genre": "Action-Adventure",
        "year": 2001,
        "developer": "Crystal Dynamics",
        "publisher": "Eidos Interactive",
        "rating": 80,
        "description": "Raziel, um vampiro transformado em espectro, viaja através do tempo para descobrir a verdade sobre seu destino e o de Nosgoth.",
        "characters": "Raziel, Kain, Moebius, Elder God",
        "gameplay_mechanics": "Viagens entre planos materiais/espectrais, combate com almas, quebra-cabeças ambientais",
        "trivia": "A narrativa complexa e questões filosóficas são frequentemente elogiadas pelos fãs.",
        "tips_easter_eggs": "Use a Soul Reaver em locais específicos para descobrir salas secretas."
    },
    {
        "title": "Ico",
        "genre": "Puzzle-Adventure",
        "year": 2001,
        "developer": "Team Ico",
        "publisher": "Sony Computer Entertainment",
        "rating": 90,
        "description": "Um menino com chifres chamado Ico ajuda uma misteriosa garota chamada Yorda a escapar de um castelo, enquanto enfrenta sombras.",
        "characters": "Ico, Yorda, A Rainha",
        "gameplay_mechanics": "Puzzles ambientais, combate simples com bastão, mecânica de segurar mãos",
        "trivia": "Influenciou fortemente o design minimalista em jogos narrativos.",
        "tips_easter_eggs": "Complete o jogo uma vez para desbloquear o modo espelhado com tradução das falas de Yorda."
    },
    {
        "title": "Steambot Chronicles",
        "genre": "RPG",
        "year": 2005,
        "developer": "Irem",
        "publisher": "Atlus",
        "rating": 71,
        "description": "Um jovem com amnésia se envolve com uma banda musical e conflitos políticos enquanto pilota um mecha customizável.",
        "characters": "Vanilla, Connie, Dandelion, Rosemary",
        "gameplay_mechanics": "Customização de Trotmobiles (mechas), instrumentos musicais jogáveis, múltiplas rotas de história",
        "trivia": "Um dos poucos RPGs que permite ao jogador escolher ser vilão em vez de herói.",
        "tips_easter_eggs": "Participe de todas as sessões musicais para melhorar suas habilidades com instrumentos."
    },
    {
        "title": "Blood Will Tell",
        "genre": "Action",
        "year": 2004,
        "developer": "WOW Entertainment",
        "publisher": "Sega",
        "rating": 69,
        "description": "Baseado no mangá Dororo, Hyakkimaru busca recuperar as 48 partes de seu corpo roubadas por demônios, com a ajuda de Dororo.",
        "characters": "Hyakkimaru, Dororo, Jukai, Tahoumaru",
        "gameplay_mechanics": "Membros protéticos com armas, habilidades desbloqueáveis, seções jogáveis como Dororo",
        "trivia": "Adaptação do clássico mangá de Osamu Tezuka dos anos 60.",
        "tips_easter_eggs": "Colete almas vermelhas para aumentar sua barra de saúde permanentemente."
    },
    {
        "title": "Digital Devil Saga",
        "genre": "RPG",
        "year": 2004,
        "developer": "Atlus",
        "publisher": "Atlus",
        "rating": 82,
        "description": "Em um mundo pós-apocalíptico chamado Junkyard, tribos em guerra ganham a habilidade de se transformar em demônios.",
        "characters": "Serph, Argilla, Heat, Cielo, Gale",
        "gameplay_mechanics": "Sistema Press Turn, transformação em demônios, Mantra Grid para habilidades",
        "trivia": "Spin-off da série Shin Megami Tensei com elementos mais filosóficos.",
        "tips_easter_eggs": "Derrote inimigos usando suas fraquezas elementais para ganhar mais pontos de habilidade."
    },
    {
        "title": "Champions of Norrath",
        "genre": "Action RPG",
        "year": 2004,
        "developer": "Snowblind Studios",
        "publisher": "Sony Online Entertainment",
        "rating": 86,
        "description": "Aventureiros embarcam em uma missão para salvar o reino de Norrath, baseado no universo de EverQuest.",
        "characters": "Classes: Bárbaro, Clérigo, Ranger, Mago, Elfo Negro",
        "gameplay_mechanics": "Dungeon crawler hack and slash, cooperativo para 4 jogadores, loot aleatório",
        "trivia": "Usado o mesmo engine de Baldur's Gate: Dark Alliance.",
        "tips_easter_eggs": "Complete o jogo na dificuldade mais alta para desbloquear o modo desafio extremo."
    },
    {
        "title": "Magna Carta: Tears of Blood",
        "genre": "RPG",
        "year": 2004,
        "developer": "Softmax",
        "publisher": "Atlus",
        "rating": 63,
        "description": "Durante uma guerra entre humanos e a raça Yason, o mercenário Calintz descobre segredos que podem mudar o curso do conflito.",
        "characters": "Calintz, Reith, Azel, Eonis",
        "gameplay_mechanics": "Sistema Trinity Circle, Chi para magias, combate por turnos",
        "trivia": "Design de personagens feito por Hyung-Tae Kim, artista coreano renomado.",
        "tips_easter_eggs": "Domine o sistema de tempo para maximizar dano em combates."
    },
    {
        "title": "Darkwatch",
        "genre": "First-Person Shooter",
        "year": 2005,
        "developer": "High Moon Studios",
        "publisher": "Capcom",
        "rating": 75,
        "description": "Jericho Cross, um ladrão de trem transformado em meio-vampiro, caça sobrenaturais no Velho Oeste americano.",
        "characters": "Jericho Cross, Cassidy Sharp, Tala, Lazarus Malkoth",
        "gameplay_mechanics": "FPS com habilidades vampíricas, sistema moral de escolhas, montaria",
        "trivia": "Mistura única de western, horror gótico e steampunk.",
        "tips_easter_eggs": "Escolhas morais durante o jogo afetam seus poderes vampíricos e o final da história."
    },
    {
        "title": "The Red Star",
        "genre": "Beat 'em up/Shoot 'em up",
        "year": 2007,
        "developer": "XS Games",
        "publisher": "XS Games",
        "rating": 70,
        "description": "Baseado no quadrinho homônimo, soldados enfrentam o exército de um tirano em uma versão alternativa da União Soviética.",
        "characters": "Makita, Kyuzo, Maya Antares",
        "gameplay_mechanics": "Híbrido de beat 'em up com shooter, ataques de protocolo (magia), bloqueio",
        "trivia": "Ficou quase completo pela Acclaim antes da empresa falir, sendo lançado anos depois.",
        "tips_easter_eggs": "Economize energia de protocolo para enfrentar os chefes mais difíceis."
    },
    {
        "title": "Primal",
        "genre": "Action-Adventure",
        "year": 2003,
        "developer": "SCE Cambridge Studio",
        "publisher": "Sony Computer Entertainment",
        "rating": 72,
        "description": "Jen, após um ataque que deixa seu namorado em coma, descobre que pode viajar entre reinos demoníacos para restaurar o equilíbrio.",
        "characters": "Jen, Scree, Abaddon, Belahzur",
        "gameplay_mechanics": "Transformação em diferentes demônios, parceiro gárgula, puzzles com dois personagens",
        "trivia": "Conta com a voz e aparência da cantora da banda KMFDM, Lucia Cifarelli.",
        "tips_easter_eggs": "Use as diferentes formas demoníacas estrategicamente dependendo do ambiente."
    },
    {
        "title": "Samurai Western",
        "genre": "Action",
        "year": 2005,
        "developer": "Acquire",
        "publisher": "Atlus",
        "rating": 58,
        "description": "O samurai Gojiro Kiryu viaja ao Velho Oeste americano para encontrar seu irmão, enfrentando foras-da-lei com sua katana.",
        "characters": "Gojiro Kiryu, Ralph, Joshua",
        "gameplay_mechanics": "Hack and slash, deflexão de balas, trajes com habilidades especiais",
        "trivia": "Spin-off da série Way of the Samurai.",
        "tips_easter_eggs": "Encontre todos os trajes escondidos para desbloquear habilidades únicas."
    },
    {
        "title": "Contra: Shattered Soldier",
        "genre": "Run and Gun",
        "year": 2002,
        "developer": "Konami",
        "publisher": "Konami",
        "rating": 80,
        "description": "Os soldados Bill Rizer e Lucia são enviados para combater a organização terrorista Blood Falcon.",
        "characters": "Bill Rizer, Lucia, Lance Bean",
        "gameplay_mechanics": "Run and gun clássico, sistema de três armas, ranking por hits",
        "trivia": "Retorno às raízes da série após experimentos 3D malsucedidos.",
        "tips_easter_eggs": "Destrua 100% dos alvos em cada nível para obter o ranking S e ver o final verdadeiro."
    },
    {
        "title": "Tenchu: Wrath of Heaven",
        "genre": "Stealth",
        "year": 2003,
        "developer": "K2",
        "publisher": "Activision",
        "rating": 79,
        "description": "Ninjas do clã Azuma enfrentam inimigos sobrenaturais em missões de assassinato e espionagem no Japão feudal.",
        "characters": "Rikimaru, Ayame, Tesshu",
        "gameplay_mechanics": "Stealth, movimentos ninjas, itens especiais, execuções furtivas",
        "trivia": "Considerado por muitos fãs como o melhor jogo da série Tenchu.",
        "tips_easter_eggs": "Termine todas as missões com rank S para desbloquear equipamentos especiais."
    },
    {
        "title": "Grandia III",
        "genre": "RPG",
        "year": 2005,
        "developer": "Game Arts",
        "publisher": "Square Enix",
        "rating": 77,
        "description": "Yuki, um jovem que sonha em voar, e uma misteriosa garota chamada Alfina embarcam em uma aventura para salvar o mundo de um culto maligno.",
        "characters": "Yuki, Alfina, Miranda, Alonso",
        "gameplay_mechanics": "Sistema de combate por turnos com iniciativa, adiamento de ações inimigas, magias elementais",
        "trivia": "Conhecido por um dos melhores sistemas de batalha em RPGs, apesar da história mais fraca.",
        "tips_easter_eggs": "Execute combos de ataques e magias para aumentar a eficiência em batalhas."
    },
    {
        "title": "Rule of Rose",
        "genre": "Survival Horror",
        "year": 2006,
        "developer": "Punchline",
        "publisher": "Atlus",
        "rating": 59,
        "description": "Jennifer busca seu cachorro perdido em um orfanato onde é atormentada por meninas cruéis em uma história sombria e simbólica.",
        "characters": "Jennifer, Brown (cão), Diana, Wendy",
        "gameplay_mechanics": "Exploração, combate limitado, quebra-cabeças, uso do cão para encontrar pistas",
        "trivia": "Causou controvérsia na Europa e foi banido em vários países devido a seu conteúdo.",
        "tips_easter_eggs": "Use seu cão Brown frequentemente para encontrar itens escondidos essenciais."
    },
    {
        "title": "Valkyrie Profile 2: Silmeria",
        "genre": "RPG",
        "year": 2006,
        "developer": "tri-Ace",
        "publisher": "Square Enix",
        "rating": 84,
        "description": "A princesa Alicia é possuída pela valquíria rebelde Silmeria, que busca impedir os planos de Odin e dos deuses.",
        "characters": "Alicia/Silmeria, Rufus, Dylan/Brahms, Lezard",
        "gameplay_mechanics": "Combate em tempo real com elementos por turnos, Photons, recrutamento de einherjar",
        "trivia": "Prequel do jogo original do PlayStation 1, explorando mais a mitologia nórdica.",
        "tips_easter_eggs": "Use a captura de Photons para congelar inimigos e obter bônus de ataque."
    },
    {
        "title": "GrimGrimoire",
        "genre": "Real-Time Strategy",
        "year": 2007,
        "developer": "Vanillaware",
        "publisher": "Nippon Ichi Software",
        "rating": 74,
        "description": "A estudante de magia Lillet Blan vive o mesmo período de cinco dias repetidamente, tentando impedir uma catástrofe na academia.",
        "characters": "Lillet Blan, Gammel Dore, Advocat, Grimlet",
        "gameplay_mechanics": "RTS 2D, invocação de familiares, quatro escolas de magia, ciclo de tempo",
        "trivia": "Desenvolvido pela Vanillaware, conhecida por seus visuais artísticos únicos.",
        "tips_easter_eggs": "Domine a escola de magia Necromancia para criar estratégias econômicas poderosas."
    },
    {
        "title": "Ibara",
        "genre": "Shoot 'em up",
        "year": 2006,
        "developer": "Cave",
        "publisher": "Taito",
        "rating": 71,
        "description": "Shooter vertical onde pilotos enfrentam a ameaça biomecânica Rose Garden, conhecida por sua dificuldade extrema.",
        "characters": "Prope, Dista, pilotos jogáveis",
        "gameplay_mechanics": "Bullet hell, rank system, chain combo, sistema de medals",
        "trivia": "Criado pela Cave, empresa lendária de shooters arcade.",
        "tips_easter_eggs": "Colete as medalhas em ordem numérica para maximizar a pontuação."
    },
    {
        "title": "Robot Alchemic Drive",
        "genre": "Action",
        "year": 2002,
        "developer": "Sandlot",
        "publisher": "Enix",
        "rating": 78,
        "description": "O jogador controla enormes robôs à distância para defender a Terra contra invasores alienígenas.",
        "characters": "Naoto Tsukioka, Ryo Kobayashi, Yui Tsukioka",
        "gameplay_mechanics": "Controle de robôs gigantes em terceira pessoa, dois analógicos para movimentos",
        "trivia": "Um dos poucos jogos que captura efetivamente a sensação de controlar robots gigantes.",
        "tips_easter_eggs": "Use ataques especiais para derrotar inimigos mais rapidamente, mas cuidado com o superaquecimento."
    },
    {
        "title": "Ar tonelico: Melody of Elemia",
        "genre": "RPG",
        "year": 2006,
        "developer": "Gust",
        "publisher": "NIS America",
        "rating": 73,
        "description": "Em um mundo onde a música tem poder mágico, Lyner deve salvar a última torre da humanidade com a ajuda de Reyvateils, garotas com poderes musicais.",
        "characters": "Lyner Barsett, Aurica Nestmile, Misha Arsellec Lune",
        "gameplay_mechanics": "Combate por turnos, Dive system para explorar mentes das Reyvateils, Song Magic",
        "trivia": "Conhecido por sua trilha sonora excepcional e linguagem fictícia cantada.",
        "tips_easter_eggs": "Fortaleça os laços com as Reyvateils através do sistema Dive para desbloquear magias poderosas."
    },
    {
        "title": "Shin Megami Tensei: Digital Devil Saga 2",
        "genre": "RPG",
        "year": 2005,
        "developer": "Atlus",
        "publisher": "Atlus",
        "rating": 83,
        "description": "Continuação direta do primeiro jogo, onde os sobreviventes chegam ao mundo real devastado e continuam sua busca pelo Nirvana.",
        "characters": "Serph, Sera, Heat, Argilla, Gale, Cielo",
        "gameplay_mechanics": "Press Turn battle system, transformação em demônios aprimorada, Solar Noise",
        "trivia": "Conclusão da história que explora temas de reencarnação e identidade.",
        "tips_easter_eggs": "O sistema Solar Noise afeta encontros aleatórios; use-o estrategicamente para farming."
    },
    {
        "title": "Chulip",
        "genre": "Adventure",
        "year": 2002,
        "developer": "Punchline",
        "publisher": "Victor Interactive Software",
        "rating": 61,
        "description": "Um menino em uma estranha vila deve beijar seus excêntricos moradores para ganhar aceitação e conquistar sua amada.",
        "characters": "Protagonista sem nome, moradores bizarros da vila",
        "gameplay_mechanics": "Social simulation, puzzles, timing para beijos, ciclo dia/noite",
        "trivia": "Jogo cult japonês conhecido por seu humor peculiar e premissa única.",
        "tips_easter_eggs": "Observe a rotina dos habitantes para determinar o melhor momento para interagir com eles."
    },
    {
        "title": "Rayman 3: Hoodlum Havoc",
        "genre": "Platformer",
        "year": 2003,
        "developer": "Ubisoft",
        "publisher": "Ubisoft",
        "rating": 77,
        "description": "Rayman deve salvar o mundo de André, um Lum Negro que transformou outros Lums em criaturas malvadas chamadas Hoodlums.",
        "characters": "Rayman, Globox, Murfy, André",
        "gameplay_mechanics": "Plataforma 3D, poderes temporários em latas, sistema de combos e pontuação",
        "trivia": "Tom mais sombrio e humorístico que os jogos anteriores da série.",
        "tips_easter_eggs": "Colete o máximo de pedras preciosas para desbloquear bônus de arte conceitual."
    },
    {
        "title": "Shadow Hearts: Covenant",
        "genre": "RPG",
        "year": 2004,
        "developer": "Nautilus",
        "publisher": "Midway",
        "rating": 85,
        "description": "Yuri Hyuga reencontra seus aliados durante a Primeira Guerra Mundial para enfrentar uma organização secreta chamada Sapientes Gladio.",
        "characters": "Yuri Hyuga, Karin Koenig, Nicolai, Anastasia",
        "gameplay_mechanics": "Judgment Ring aprimorado, Fusion Monsters, combos em grupo",
        "trivia": "Mescla eventos históricos reais com elementos sobrenaturais e humor.",
        "tips_easter_eggs": "Complete as sidequests para obter as fusões mais poderosas para Yuri."
    },
    {
        "title": "Kuon",
        "genre": "Survival Horror",
        "year": 2004,
        "developer": "FromSoftware",
        "publisher": "Agetec",
        "rating": 70,
        "description": "Ambientado no Japão feudal, narra a história de três personagens envolvidos em eventos sobrenaturais em uma mansão amaldiçoada.",
        "characters": "Utsuki, Sakuya, Doman",
        "gameplay_mechanics": "Horror com câmera fixa, diferentes campanhas por personagem, magias orientais",
        "trivia": "Baseado em lendas do folclore japonês e desenvolvido pela FromSoftware.",
        "tips_easter_eggs": "Economize seus itens de cura; eles são extremamente raros no jogo."
    },
    {
        "title": "Chaos Legion",
        "genre": "Action Hack and Slash",
        "year": 2003,
        "developer": "Capcom",
        "publisher": "Capcom",
        "rating": 65,
        "description": "Sieg Wahrheit usa legiões de monstros invocados para combater as forças de seu ex-amigo Victor Delacroix.",
        "characters": "Sieg Wahrheit, Victor Delacroix, Siela Riviere",
        "gameplay_mechanics": "Hack and slash com sistema de legiões como unidades de suporte",
        "trivia": "O conceito artístico foi inspirado na obra do escritor japonês Tow Ubukata.",
        "tips_easter_eggs": "Desenvolva a legião Sword antes das outras para facilitar combates iniciais."
    },
    {
        "title": "Michigan: Report from Hell",
        "genre": "Survival Horror",
        "year": 2004,
        "developer": "Grasshopper Manufacture",
        "publisher": "Spike",
        "rating": 43,
        "description": "Um cinegrafista acompanha repórteres para cobrir uma misteriosa névoa em Chicago que transforma pessoas em monstros.",
        "characters": "Protagonista não nomeado (cinegrafista), Brisco, Pamela",
        "gameplay_mechanics": "Gameplay em primeira pessoa através de uma câmera, sistema de medo, diferentes finais",
        "trivia": "Dirigido por Suda51, conhecido por jogos com narrativas não-convencionais como Killer7.",
        "tips_easter_eggs": "Filme eventos específicos para aumentar seu rank de jornalismo e desbloquear finais melhores."
    },
{
       "title": "Drakengard",
       "genre": "Action RPG",
       "year": 2003,
       "developer": "Cavia",
       "publisher": "Square Enix",
       "rating": 63,
       "description": "Caim forma um pacto com um dragão vermelho para salvar sua irmã e impedir que o Império use magia proibida para ressuscitar deuses malignos.",
       "characters": "Caim, Angelus (dragão), Furiae, Inuart",
       "gameplay_mechanics": "Combate hack and slash em solo, batalhas aéreas com dragão, múltiplos finais",
       "trivia": "Drakengard tem uma conexão direta com NieR, já que um de seus finais leva aos eventos desse jogo.",
       "tips_easter_eggs": "Complete todas as armas para desbloquear o caminho para o final E, o mais difícil e bizarro."
   }
]

# Criar e configurar o DataFrame
df = pd.DataFrame(ps2_games_database)

# Função para salvar e visualizar o CSV
def save_and_show_games(df):
   csv_path = "ps2_games_database.csv"
   df.to_csv(csv_path, index=False, encoding='utf-8')
   print(f"Database salvo com sucesso em {csv_path}")
   print(f"Total de jogos: {len(df)}")
   return df

# Executar a função principal
if __name__ == "__main__":
   complete_db = save_and_show_games(df)
   print("\nPrimeiras entradas do banco de dados:")
   print(complete_db.head(3))
   print("\nÚltimas entradas do banco de dados:")
   print(complete_db.tail(3))